### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by koikic** [LordMike/TMDbLib#163]
Hey LordMike,

Thanks for you work.

I have some problem when i want to use your API on Windows 10 : Universal APP,

Following errors : 

Install-Package : TMDbLib 0.8.3 is not compatible with UAP,Version=v10.0.
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : RestSharp 104.4.0 is not compatible with UAP,Version=v10.0.
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0.
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : TMDbLib 0.8.3 is not compatible with UAP,Version=v10.0 (win10-arm).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : RestSharp 104.4.0 is not compatible with UAP,Version=v10.0 (win10-arm).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : TMDbLib 0.8.3 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : RestSharp 104.4.0 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : TMDbLib 0.8.3 is not compatible with UAP,Version=v10.0 (win10-x86).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : RestSharp 104.4.0 is not compatible with UAP,Version=v10.0 (win10-x86).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : TMDbLib 0.8.3 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : RestSharp 104.4.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : TMDbLib 0.8.3 is not compatible with UAP,Version=v10.0 (win10-x64).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : RestSharp 104.4.0 is not compatible with UAP,Version=v10.0 (win10-x64).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : TMDbLib 0.8.3 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : RestSharp 104.4.0 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 
Échec de la restauration des packages pour 'SmartVideoManager'.
Install-Package : Échec de la restauration du package. Restauration des modifications du package pour 
'SmartVideoManager'.
Au caractère Ligne:1 : 1
+ Install-Package TMDbLib -Version 0.8.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command
 

----

It's say that some packages in your API are not compatible with Windows 10 UAP.

Is it possible for you to fix it ?

Best regards

**Comment by Naliath** [comment]
we are aware of the issue. We need to remove the RestSharp dependency and replace it with System.Net.Http, but as of yet neither of us has had the time to do this. If you care to give it a shot feel free to kick over a pull request and we will review it.

**Comment by koikic** [comment]
Thanks for your reply, i'will see, if I can change the reference.

**Comment by LordMike** [comment]
@koikic I just pushed a version `0.9.0.0-alpha` to Nuget. Could you try that out?

**Comment by crega** [comment]
Hey, I'm new to c# I have project to make use of this Library. i intent to create Win10 UWP that works on Desktop and Mobile device.How can I use classes from TMDBLib project in my own project. I tried to reference TMDBLib project to my project but it won't allow it to me. Then I added in same solution 3 projects that You provided (LibTest Lib and Test) still no luck. I hope I am not boring with this amateur questions. Thank You!

**Comment by Naliath** [comment]
@crega try to use the nuget package referenced by LordMike (do not forget to check the include prerelease option). For more info about nuget I suggest you google around a bit, there is plenty of info out there. This is also only the first version that should work with UWA's so it might not work that well... 

In all honesty if you are just starting out you be better off just following some of the tutorials over on https://msdn.microsoft.com/en-us/library/windows/apps/dn765018.aspx. 

But naturally you are more than welcome to try out the alpha we just released, just know it is a first version.

**Comment by mike-csis** [comment]
@crega we haven't actually gotten to the point of supporting UWP's yet. Once I get more time, I can perhaps make the final push towards getting a version that will compile, and hopefully work, with .NET PCL. No we at least have the dependencies out of the way ;).

**Comment by LordMike** [comment]
@crega we haven't actually gotten to the point of supporting UWP's yet. Once I get more time, I can perhaps make the final push towards getting a version that will compile, and hopefully work, with .NET PCL. No we at least have the dependencies out of the way ;).

**Comment by crega** [comment]
Oh i GET It now , its ok untill then I will use another library that is
compatible
uto, 26. sij 2016. u 15:50 Michael Bisbjerg <notifications@github.com>
napisao je:

**Comment by Naliath** [comment]
Gonna just close this up, please refer to #44. When that issue is resolved so will this
